--- #YAML:1.0
name:                File-Strmode
version:             0.01
abstract:            Converts a file mode into a symbolic string
license:             ~
author:              
    - salva <salva@>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
